services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: inventory_db
      MARIADB_USER: app
      MARIADB_PASSWORD: "12345678"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inventory_net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - inventory_net

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/mywebapp.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - inventory_net

volumes:
  db_data:

networks:
  inventory_net:
    driver: bridge
