server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/mywebapp_access.log;
    error_log  /var/log/nginx/mywebapp_error.log;

    location = / {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
    }

    location /items {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
    }

    location / {
        return 404;
    }
}