#cloud-config
users:
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBBf+v5WQG7y/iA0umP346ts0YmriFbKG3FnkyW2r0B2 artem@LAPTOP-PLRK786C
  - name: teacher
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) ALL
    lock_passwd: false
    passwd: "$6$rounds=4096$saltsalt$hashedpassword"
  - name: operator
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$rounds=4096$saltsalt$hashedpassword"

package_update: true
packages:
  - qemu-guest-agent

runcmd:
  - echo "teacher:12345678" | chpasswd
  - echo "operator:12345678" | chpasswd
  - systemctl enable qemu-guest-agent
