#cloud-config
users:
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBBF+v5WQG7y/iA0umP346ts0YmriFbKG3FnkyW2r0B2 artem@LAPTOP-PLRK786C
ssh_pwauth: true
