---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Configure nginx
  ansible.builtin.template:
    src: mywebapp.conf.j2
    dest: /etc/nginx/sites-available/mywebapp
    mode: '0644'
  notify: Reload nginx

- name: Enable nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mywebapp
    dest: /etc/nginx/sites-enabled/mywebapp
    state: link

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Start and enable nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true